name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew --no-daemon build jib
        env:
          BUILD_NUMBER: ${{ github.sha }}
          CONTAINER_NAME: pdgwien/discord-thanksbot
          DOCKER_USERNAME: ${{ secrets.DockerUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
